-- 답변

insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	1	,	'힘내세요!! 이 사이트를 한번 참고해보세요'	,	1	,	1	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	2	,	'매니저님께 한번 물어보세요 나중 수업시간에 알려드리도록 하겠습니다.'	,	4	,	2	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	3	,	'한번 더 고민해보세요 추천도서목록을 참고해주세요'	,	1	,	3	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	4	,	'매니저님께 한번 물어보세요 자세한 사항은 내일 수업 시간 때 알려드리도록 하겠습니다.'	,	4	,	4	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	5	,	'나중 수업시간에 알려드리도록 하겠습니다. 복습 시간을 조금 더 늘리는 것을 추천드립니다.'	,	4	,	5	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	6	,	'추천도서목록을 참고해주세요 추천도서목록을 참고해주세요'	,	4	,	6	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	7	,	'매니저님께 한번 물어보세요 나중 수업시간에 알려드리도록 하겠습니다.'	,	4	,	7	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	8	,	'자세한 사항은 내일 수업 시간 때 알려드리도록 하겠습니다. 힘내세요!!'	,	4	,	8	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	9	,	'걱정하지 않으셔도 됩니다. 한번 더 고민해보세요'	,	1	,	9	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	10	,	'나중 수업시간에 알려드리도록 하겠습니다. 큰 문제는 아닙니다.'	,	4	,	10	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	11	,	'답변 드렸습니다. 힘내세요!!'	,	1	,	11	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	12	,	'중요한 문제는 아니니 넘어가셔도 상관 없습니다 복습 시간을 조금 더 늘리는 것을 추천드립니다.'	,	1	,	12	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	13	,	'자세한 사항은 내일 수업 시간 때 알려드리도록 하겠습니다. 매니저님께 한번 물어보세요'	,	1	,	13	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	14	,	'한번 더 고민해보세요 중요한 문제는 아니니 넘어가셔도 상관 없습니다'	,	4	,	14	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	15	,	'추천도서목록을 참고해주세요 자세한 사항은 내일 수업 시간 때 알려드리도록 하겠습니다.'	,	4	,	15	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	16	,	'이 사이트를 한번 참고해보세요 나중 수업시간에 알려드리도록 하겠습니다.'	,	1	,	16	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	17	,	'나중 수업시간에 알려드리도록 하겠습니다. 답변 드렸습니다.'	,	7	,	17	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	18	,	'추천도서목록을 참고해주세요 한번 더 고민해보세요'	,	4	,	18	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	19	,	'걱정하지 않으셔도 됩니다. 걱정하지 않으셔도 됩니다.'	,	7	,	19	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	20	,	'답변 드렸습니다. 힘내세요!!'	,	1	,	20	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	21	,	'중요한 문제는 아니니 넘어가셔도 상관 없습니다 걱정하지 않으셔도 됩니다.'	,	4	,	21	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	22	,	'중요한 문제는 아니니 넘어가셔도 상관 없습니다 복습 시간을 조금 더 늘리는 것을 추천드립니다.'	,	5	,	22	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	23	,	'나중 수업시간에 알려드리도록 하겠습니다. 답변 드렸습니다.'	,	4	,	23	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	24	,	'이 사이트를 한번 참고해보세요 큰 문제는 아닙니다.'	,	4	,	24	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	25	,	'자세한 사항은 내일 수업 시간 때 알려드리도록 하겠습니다. 답변 드렸습니다.'	,	1	,	25	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	26	,	'중요한 문제는 아니니 넘어가셔도 상관 없습니다 자세한 사항은 내일 수업 시간 때 알려드리도록 하겠습니다.'	,	7	,	26	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	27	,	'큰 문제는 아닙니다. 추천도서목록을 참고해주세요'	,	5	,	27	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	28	,	'복습 시간을 조금 더 늘리는 것을 추천드립니다. 자세한 사항은 내일 수업 시간 때 알려드리도록 하겠습니다.'	,	1	,	28	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	29	,	'추천도서목록을 참고해주세요 나중 수업시간에 알려드리도록 하겠습니다.'	,	1	,	29	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	30	,	'추천도서목록을 참고해주세요 한번 더 고민해보세요'	,	1	,	30	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	31	,	'매니저님께 한번 물어보세요 이 사이트를 한번 참고해보세요'	,	4	,	31	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	32	,	'이 사이트를 한번 참고해보세요 추천도서목록을 참고해주세요'	,	4	,	32	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	33	,	'중요한 문제는 아니니 넘어가셔도 상관 없습니다 이 사이트를 한번 참고해보세요'	,	1	,	33	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	34	,	'큰 문제는 아닙니다. 한번 더 고민해보세요'	,	1	,	34	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	35	,	'매니저님께 한번 물어보세요 답변 드렸습니다.'	,	10	,	35	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	37	,	'걱정하지 않으셔도 됩니다. 한번 더 고민해보세요'	,	7	,	37	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	38	,	'답변 드렸습니다. 중요한 문제는 아니니 넘어가셔도 상관 없습니다'	,	10	,	38	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	39	,	'추천도서목록을 참고해주세요 매니저님께 한번 물어보세요'	,	5	,	39	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	40	,	'복습 시간을 조금 더 늘리는 것을 추천드립니다. 걱정하지 않으셔도 됩니다.'	,	5	,	40	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	41	,	'추천도서목록을 참고해주세요 매니저님께 한번 물어보세요'	,	1	,	41	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	42	,	'자세한 사항은 내일 수업 시간 때 알려드리도록 하겠습니다. 큰 문제는 아닙니다.'	,	4	,	42	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	43	,	'자세한 사항은 내일 수업 시간 때 알려드리도록 하겠습니다. 답변 드렸습니다.'	,	1	,	43	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	44	,	'한번 더 고민해보세요 이 사이트를 한번 참고해보세요'	,	5	,	44	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	45	,	'큰 문제는 아닙니다. 한번 더 고민해보세요'	,	7	,	45	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	46	,	'한번 더 고민해보세요 걱정하지 않으셔도 됩니다.'	,	4	,	46	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	47	,	'복습 시간을 조금 더 늘리는 것을 추천드립니다. 큰 문제는 아닙니다.'	,	7	,	47	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	48	,	'자세한 사항은 내일 수업 시간 때 알려드리도록 하겠습니다. 큰 문제는 아닙니다.'	,	4	,	48	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	49	,	'힘내세요!! 답변 드렸습니다.'	,	5	,	49	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	50	,	'큰 문제는 아닙니다. 큰 문제는 아닙니다.'	,	5	,	50	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	51	,	'큰 문제는 아닙니다. 힘내세요!!'	,	5	,	51	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	52	,	'답변 드렸습니다. 중요한 문제는 아니니 넘어가셔도 상관 없습니다'	,	1	,	52	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	53	,	'이 사이트를 한번 참고해보세요 중요한 문제는 아니니 넘어가셔도 상관 없습니다'	,	4	,	53	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	54	,	'이 사이트를 한번 참고해보세요 자세한 사항은 내일 수업 시간 때 알려드리도록 하겠습니다.'	,	1	,	54	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	55	,	'중요한 문제는 아니니 넘어가셔도 상관 없습니다 자세한 사항은 내일 수업 시간 때 알려드리도록 하겠습니다.'	,	1	,	55	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	56	,	'복습 시간을 조금 더 늘리는 것을 추천드립니다. 매니저님께 한번 물어보세요'	,	1	,	56	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	57	,	'걱정하지 않으셔도 됩니다. 나중 수업시간에 알려드리도록 하겠습니다.'	,	4	,	57	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	58	,	'중요한 문제는 아니니 넘어가셔도 상관 없습니다 추천도서목록을 참고해주세요'	,	7	,	58	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	59	,	'추천도서목록을 참고해주세요 답변 드렸습니다.'	,	5	,	59	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	60	,	'이 사이트를 한번 참고해보세요 자세한 사항은 내일 수업 시간 때 알려드리도록 하겠습니다.'	,	4	,	60	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	61	,	'매니저님께 한번 물어보세요 큰 문제는 아닙니다.'	,	1	,	61	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	62	,	'나중 수업시간에 알려드리도록 하겠습니다. 추천도서목록을 참고해주세요'	,	10	,	62	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	63	,	'한번 더 고민해보세요 힘내세요!!'	,	5	,	63	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	64	,	'걱정하지 않으셔도 됩니다. 이 사이트를 한번 참고해보세요'	,	1	,	64	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	65	,	'자세한 사항은 내일 수업 시간 때 알려드리도록 하겠습니다. 매니저님께 한번 물어보세요'	,	1	,	65	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	66	,	'자세한 사항은 내일 수업 시간 때 알려드리도록 하겠습니다. 한번 더 고민해보세요'	,	4	,	66	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	67	,	'자세한 사항은 내일 수업 시간 때 알려드리도록 하겠습니다. 큰 문제는 아닙니다.'	,	7	,	67	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	68	,	'큰 문제는 아닙니다. 힘내세요!!'	,	4	,	68	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	69	,	'이 사이트를 한번 참고해보세요 한번 더 고민해보세요'	,	7	,	69	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	70	,	'걱정하지 않으셔도 됩니다. 답변 드렸습니다.'	,	5	,	70	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	71	,	'이 사이트를 한번 참고해보세요 복습 시간을 조금 더 늘리는 것을 추천드립니다.'	,	5	,	71	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	72	,	'답변 드렸습니다. 추천도서목록을 참고해주세요'	,	1	,	72	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	73	,	'추천도서목록을 참고해주세요 답변 드렸습니다.'	,	4	,	73	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	74	,	'자세한 사항은 내일 수업 시간 때 알려드리도록 하겠습니다. 걱정하지 않으셔도 됩니다.'	,	1	,	74	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	75	,	'매니저님께 한번 물어보세요 추천도서목록을 참고해주세요'	,	7	,	75	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	76	,	'자세한 사항은 내일 수업 시간 때 알려드리도록 하겠습니다. 매니저님께 한번 물어보세요'	,	4	,	76	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	77	,	'걱정하지 않으셔도 됩니다. 중요한 문제는 아니니 넘어가셔도 상관 없습니다'	,	4	,	77	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	78	,	'추천도서목록을 참고해주세요 자세한 사항은 내일 수업 시간 때 알려드리도록 하겠습니다.'	,	5	,	78	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	79	,	'힘내세요!! 복습 시간을 조금 더 늘리는 것을 추천드립니다.'	,	1	,	79	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	80	,	'한번 더 고민해보세요 큰 문제는 아닙니다.'	,	4	,	80	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	81	,	'한번 더 고민해보세요 한번 더 고민해보세요'	,	1	,	81	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	82	,	'힘내세요!! 한번 더 고민해보세요'	,	1	,	82	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	83	,	'자세한 사항은 내일 수업 시간 때 알려드리도록 하겠습니다. 매니저님께 한번 물어보세요'	,	4	,	83	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	84	,	'매니저님께 한번 물어보세요 자세한 사항은 내일 수업 시간 때 알려드리도록 하겠습니다.'	,	7	,	84	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	85	,	'이 사이트를 한번 참고해보세요 매니저님께 한번 물어보세요'	,	5	,	85	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	86	,	'복습 시간을 조금 더 늘리는 것을 추천드립니다. 매니저님께 한번 물어보세요'	,	1	,	86	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	87	,	'걱정하지 않으셔도 됩니다. 힘내세요!!'	,	10	,	87	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	88	,	'중요한 문제는 아니니 넘어가셔도 상관 없습니다 매니저님께 한번 물어보세요'	,	5	,	88	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	89	,	'답변 드렸습니다. 중요한 문제는 아니니 넘어가셔도 상관 없습니다'	,	4	,	89	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	90	,	'중요한 문제는 아니니 넘어가셔도 상관 없습니다 자세한 사항은 내일 수업 시간 때 알려드리도록 하겠습니다.'	,	1	,	90	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	91	,	'큰 문제는 아닙니다. 추천도서목록을 참고해주세요'	,	1	,	91	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	92	,	'나중 수업시간에 알려드리도록 하겠습니다. 답변 드렸습니다.'	,	4	,	92	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	93	,	'나중 수업시간에 알려드리도록 하겠습니다. 한번 더 고민해보세요'	,	7	,	93	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	94	,	'복습 시간을 조금 더 늘리는 것을 추천드립니다. 힘내세요!!'	,	4	,	94	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	95	,	'힘내세요!! 답변 드렸습니다.'	,	4	,	95	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	96	,	'힘내세요!! 중요한 문제는 아니니 넘어가셔도 상관 없습니다'	,	4	,	96	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	97	,	'답변 드렸습니다. 걱정하지 않으셔도 됩니다.'	,	4	,	97	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	98	,	'나중 수업시간에 알려드리도록 하겠습니다. 나중 수업시간에 알려드리도록 하겠습니다.'	,	5	,	98	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	99	,	'걱정하지 않으셔도 됩니다. 나중 수업시간에 알려드리도록 하겠습니다.'	,	1	,	99	);
insert into tblAnswer (answer_seq, answer_txt, teacher_seq,  consult_seq ) values(	100	,	'추천도서목록을 참고해주세요 복습 시간을 조금 더 늘리는 것을 추천드립니다.'	,	1	,	100	);