-- 상담

insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	1	,	'어디서 오류가 난건지 못찾겠어요 팀 프로젝트 관련 질문이 있습니다.'	,	57	,	61	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	2	,	'중도탈락 관련 상담하고 싶습니다 도와주세요!!'	,	129	,	151	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	3	,	'도와주세요!! 어디서 오류가 난건지 못찾겠어요'	,	57	,	73	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	4	,	'어디서 오류가 난건지 못찾겠어요 시험 걸과 관련해서 질문 드립니다.'	,	129	,	180	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	5	,	'질문 있어요!! 진도를 따라가기가 힘들어요'	,	129	,	173	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	6	,	'어디서 오류가 난건지 못찾겠어요 실무에서도 이렇게 하나요?'	,	128	,	151	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	7	,	'시험 걸과 관련해서 질문 드립니다. 시험 걸과 관련해서 질문 드립니다.'	,	128	,	180	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	8	,	'출석 관련 처리는 어떻게 해야 하나요 실무에서도 이렇게 하나요?'	,	128	,	156	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	9	,	'진도가 너무 빨라요 교재말고 참고해야 할 도서가 있나요?'	,	57	,	90	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	10	,	'수업 난이도가 너무 낮은 것 같아요 교재말고 참고해야 할 도서가 있나요?'	,	129	,	162	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	11	,	'중도탈락 관련 상담하고 싶습니다 시험 걸과 관련해서 질문 드립니다.'	,	2	,	1	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	12	,	'실무에서도 이렇게 하나요? 출석 관련 처리는 어떻게 해야 하나요'	,	57	,	86	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	13	,	'어디서 오류가 난건지 못찾겠어요 시험 걸과 관련해서 질문 드립니다.'	,	57	,	82	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	14	,	'중도탈락 관련 상담하고 싶습니다 실무에서도 이렇게 하나요?'	,	128	,	168	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	15	,	'팀 프로젝트 관련 질문이 있습니다. 질문 있어요!!'	,	129	,	168	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	16	,	'시험 걸과 관련해서 질문 드립니다. 수업 난이도가 너무 낮은 것 같아요'	,	2	,	18	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	17	,	'질문 있어요!! 시험 걸과 관련해서 질문 드립니다.'	,	89	,	121	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	18	,	'어디서 오류가 난건지 못찾겠어요 도와주세요!!'	,	129	,	157	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	19	,	'교재말고 참고해야 할 도서가 있나요? 중도탈락 관련 상담하고 싶습니다'	,	89	,	141	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	20	,	'출석 관련 처리는 어떻게 해야 하나요 도와주세요!!'	,	57	,	62	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	21	,	'수업 난이도가 너무 낮은 것 같아요 시험 걸과 관련해서 질문 드립니다.'	,	129	,	172	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	22	,	'어디서 오류가 난건지 못찾겠어요 진도를 따라가기가 힘들어요'	,	23	,	44	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	23	,	'팀 프로젝트 관련 질문이 있습니다. 어디서 오류가 난건지 못찾겠어요'	,	128	,	157	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	24	,	'진도를 따라가기가 힘들어요 중도탈락 관련 상담하고 싶습니다'	,	128	,	180	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	25	,	'진도를 따라가기가 힘들어요 시험 걸과 관련해서 질문 드립니다.'	,	2	,	17	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	26	,	'진도가 너무 빨라요 진도를 따라가기가 힘들어요'	,	89	,	145	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	27	,	'수업 난이도가 너무 낮은 것 같아요 진도를 따라가기가 힘들어요'	,	23	,	31	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	28	,	'시험 걸과 관련해서 질문 드립니다. 수업 난이도가 너무 낮은 것 같아요'	,	58	,	65	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	29	,	'출석 관련 처리는 어떻게 해야 하나요 도와주세요!!'	,	58	,	84	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	30	,	'교재말고 참고해야 할 도서가 있나요? 출석 관련 처리는 어떻게 해야 하나요'	,	58	,	68	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	31	,	'도와주세요!! 진도를 따라가기가 힘들어요'	,	70	,	120	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	32	,	'출석 관련 처리는 어떻게 해야 하나요 진도를 따라가기가 힘들어요'	,	70	,	104	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	33	,	'진도를 따라가기가 힘들어요 포트폴리오 관련해서 질문하고 싶습니다'	,	55	,	70	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	34	,	'질문 있어요!! 진도가 너무 빨라요'	,	55	,	89	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	35	,	'시험 걸과 관련해서 질문 드립니다. 출석 관련 처리는 어떻게 해야 하나요'	,	144	,	197	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	36	,	'중도탈락 관련 상담하고 싶습니다 질문 있어요!!'	,	24	,		5);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	37	,	'중도탈락 관련 상담하고 싶습니다 시험 걸과 관련해서 질문 드립니다.'	,	89	,	128	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	38	,	'시험 걸과 관련해서 질문 드립니다. 실무에서도 이렇게 하나요?'	,	144	,	183	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	39	,	'포트폴리오 관련해서 질문하고 싶습니다 포트폴리오 관련해서 질문하고 싶습니다'	,	26	,	31	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	40	,	'수업 난이도가 너무 낮은 것 같아요 도와주세요!!'	,	28	,	31	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	41	,	'실무에서도 이렇게 하나요? 수업 난이도가 너무 낮은 것 같아요'	,	1	,	30	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	42	,	'교재말고 참고해야 할 도서가 있나요? 출석 관련 처리는 어떻게 해야 하나요'	,	72	,	96	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	43	,	'중도탈락 관련 상담하고 싶습니다 포트폴리오 관련해서 질문하고 싶습니다'	,	5	,	23	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	44	,	'추가적으로 참고해야 할 사이트가 있을까요? 추가적으로 참고해야 할 사이트가 있을까요?'	,	24	,	47	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	45	,	'진도를 따라가기가 힘들어요 수업 난이도가 너무 낮은 것 같아요'	,	93	,	123	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	46	,	'질문 있어요!! 실무에서도 이렇게 하나요?'	,	125	,	153	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	47	,	'실무에서도 이렇게 하나요? 추가적으로 참고해야 할 사이트가 있을까요?'	,	89	,	150	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	48	,	'도와주세요!! 수업 난이도가 너무 낮은 것 같아요'	,	124	,	151	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	49	,	'팀 프로젝트 관련 질문이 있습니다. 출석 관련 처리는 어떻게 해야 하나요'	,	23	,	32	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	50	,	'팀 프로젝트 관련 질문이 있습니다. 추가적으로 참고해야 할 사이트가 있을까요?'	,	26	,	36	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	51	,	'팀 프로젝트 관련 질문이 있습니다. 출석 관련 처리는 어떻게 해야 하나요'	,	28	,	43	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	52	,	'수업 난이도가 너무 낮은 것 같아요 도와주세요!!'	,	58	,	67	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	53	,	'시험 걸과 관련해서 질문 드립니다. 교재말고 참고해야 할 도서가 있나요?'	,	70	,	100	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	54	,	'포트폴리오 관련해서 질문하고 싶습니다 진도를 따라가기가 힘들어요'	,	1	,	20	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	55	,	'질문 있어요!! 질문 있어요!!'	,	1	,	25	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	56	,	'도와주세요!! 교재말고 참고해야 할 도서가 있나요?'	,	1	,	17	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	57	,	'도와주세요!! 팀 프로젝트 관련 질문이 있습니다.'	,	125	,	158	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	58	,	'추가적으로 참고해야 할 사이트가 있을까요? 진도가 너무 빨라요'	,	93	,	129	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	59	,	'시험 걸과 관련해서 질문 드립니다. 실무에서도 이렇게 하나요?'	,	26	,	38	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	60	,	'진도가 너무 빨라요 추가적으로 참고해야 할 사이트가 있을까요?'	,	72	,	99	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	61	,	'교재말고 참고해야 할 도서가 있나요? 진도를 따라가기가 힘들어요'	,	5	,	16	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	62	,	'팀 프로젝트 관련 질문이 있습니다. 시험 걸과 관련해서 질문 드립니다.'	,	144	,	187	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	63	,	'추가적으로 참고해야 할 사이트가 있을까요? 팀 프로젝트 관련 질문이 있습니다.'	,	23	,	36	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	64	,	'도와주세요!! 팀 프로젝트 관련 질문이 있습니다.'	,	2	,	23	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	65	,	'어디서 오류가 난건지 못찾겠어요 팀 프로젝트 관련 질문이 있습니다.'	,	57	,	84	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	66	,	'시험 걸과 관련해서 질문 드립니다. 추가적으로 참고해야 할 사이트가 있을까요?'	,	72	,	113	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	67	,	'수업 난이도가 너무 낮은 것 같아요 진도를 따라가기가 힘들어요'	,	89	,	132	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	68	,	'실무에서도 이렇게 하나요? 질문 있어요!!'	,	125	,	156	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	69	,	'추가적으로 참고해야 할 사이트가 있을까요? 시험 걸과 관련해서 질문 드립니다.'	,	89	,	135	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	70	,	'어디서 오류가 난건지 못찾겠어요 진도를 따라가기가 힘들어요'	,	26	,	47	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	71	,	'출석 관련 처리는 어떻게 해야 하나요 질문 있어요!!'	,	28	,	60	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	72	,	'중도탈락 관련 상담하고 싶습니다 진도를 따라가기가 힘들어요'	,	1	,	7	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	73	,	'시험 걸과 관련해서 질문 드립니다. 질문 있어요!!'	,	72	,	110	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	74	,	'어디서 오류가 난건지 못찾겠어요 팀 프로젝트 관련 질문이 있습니다.'	,	5	,	25	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	75	,	'시험 걸과 관련해서 질문 드립니다. 중도탈락 관련 상담하고 싶습니다'	,	93	,	137	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	76	,	'도와주세요!! 어디서 오류가 난건지 못찾겠어요'	,	125	,	167	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	77	,	'포트폴리오 관련해서 질문하고 싶습니다 도와주세요!!'	,	124	,	163	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	78	,	'팀 프로젝트 관련 질문이 있습니다. 질문 있어요!!'	,	23	,	38	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	79	,	'팀 프로젝트 관련 질문이 있습니다. 어디서 오류가 난건지 못찾겠어요'	,	58	,	70	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	80	,	'어디서 오류가 난건지 못찾겠어요 도와주세요!!'	,	70	,	106	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	81	,	'포트폴리오 관련해서 질문하고 싶습니다 진도를 따라가기가 힘들어요'	,	1	,	9	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	82	,	'수업 난이도가 너무 낮은 것 같아요 교재말고 참고해야 할 도서가 있나요?'	,	1	,	8	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	83	,	'추가적으로 참고해야 할 사이트가 있을까요? 포트폴리오 관련해서 질문하고 싶습니다'	,	125	,	160	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	84	,	'출석 관련 처리는 어떻게 해야 하나요 진도를 따라가기가 힘들어요'	,	93	,	148	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	85	,	'포트폴리오 관련해서 질문하고 싶습니다 진도를 따라가기가 힘들어요'	,	26	,	59	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	86	,	'실무에서도 이렇게 하나요? 수업 난이도가 너무 낮은 것 같아요'	,	58	,	75	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	87	,	'실무에서도 이렇게 하나요? 수업 난이도가 너무 낮은 것 같아요'	,	144	,	181	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	88	,	'진도가 너무 빨라요 진도를 따라가기가 힘들어요'	,	23	,	40	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	89	,	'추가적으로 참고해야 할 사이트가 있을까요? 질문 있어요!!'	,	125	,	154	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	90	,	'중도탈락 관련 상담하고 싶습니다 교재말고 참고해야 할 도서가 있나요?'	,	2	,	20	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	91	,	'교재말고 참고해야 할 도서가 있나요? 중도탈락 관련 상담하고 싶습니다'	,	57	,	75	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	92	,	'질문 있어요!! 어디서 오류가 난건지 못찾겠어요'	,	72	,	120	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	93	,	'포트폴리오 관련해서 질문하고 싶습니다 교재말고 참고해야 할 도서가 있나요?'	,	89	,	130	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	94	,	'질문 있어요!! 중도탈락 관련 상담하고 싶습니다'	,	125	,	170	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	95	,	'팀 프로젝트 관련 질문이 있습니다. 포트폴리오 관련해서 질문하고 싶습니다'	,	124	,	155	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	96	,	'교재말고 참고해야 할 도서가 있나요? 팀 프로젝트 관련 질문이 있습니다.'	,	124	,	174	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	97	,	'어디서 오류가 난건지 못찾겠어요 출석 관련 처리는 어떻게 해야 하나요'	,	71	,	105	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	98	,	'어디서 오류가 난건지 못찾겠어요 질문 있어요!!'	,	23	,	59	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	99	,	'실무에서도 이렇게 하나요? 진도를 따라가기가 힘들어요'	,	58	,	86	);
insert into tblConsult (consult_seq, consult_txt, csub_seq, sugang_seq) values(	100	,	'실무에서도 이렇게 하나요? 출석 관련 처리는 어떻게 해야 하나요'	,	2	,	30	);