-- tblEnterprise 협력기업테이블 데이터

insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(1,'(주)재하정보기술',3,'정규직','OP','백엔드/서버개발');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(2,'매일경제MBN',3,'인턴','OP','웹개발');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(3,'BPlace',0,'계약직','OP','웹개발');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(4,'교보정보통신',3,'계약직','SI','웹개발');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(5,'GTONE',1,'인턴','SE','안드로이드 개발');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(6,'웰컴금융그룹',3,'정규직','Solution','정보보안');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(7,'피에프컨설팅',2,'인턴','SM','프론트엔드');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(8,'TmaxSoft',3,'정규직','Solution','보안컨설팅');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(9,'IMFORM',0,'계약직','SE','프론트엔드');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(10,'인사이드정보',4,'인턴','SE','정보보안');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(11,'GTPlus',1,'정규직','Solution','백엔드/서버개발');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(12,'LogosSystem',0,'정규직','OP','CPO');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(13,'대원씨앤씨',4,'정규직','Solution','CPO');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(14,'FinShot',3,'인턴','SP','보안컨설팅');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(15,'danawa',0,'계약직','OP','유지보수');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(16,'지성아이티',1,'정규직','SI','프론트엔드');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(17,'SPH',3,'계약직','OP','유지보수');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(18,'Metanet',1,'정규직','Solution','CISO');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(19,'BLUE INDEX',1,'인턴','SI','IOS개발');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(20,'trees System',0,'정규직','SM','유지보수');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(21,'beyless',1,'정규직','SI','웹개발');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(22,'ToBeWAY',2,'정규직','SE','보안컨설팅');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(23,'한살림',3,'계약직','SE','유지보수');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(24,'엠아이큐브솔루션',4,'정규직','OP','프론트엔드');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(25,'(주)부뜰정보시스템',3,'인턴','OP','CPO');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(26,'한국기술지원',2,'인턴','Solution','보안컨설팅');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(27,'위드정보',3,'계약직','SM','웹개발');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(28,'주식회사바이텍정보통신',1,'계약직','SP','CPO');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(29,'중외정보기술',2,'인턴','SE','안드로이드 개발');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(30,'아이티메세지',1,'인턴','OP','CISO');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(31,'LOTTE PS Net',4,'계약직','SP','IOS개발');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(32,'브이앤지',1,'인턴','OP','IOS개발');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(33,'DANUSYS',2,'인턴','SP','정보보안');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(34,'KRP',4,'계약직','Solution','웹개발');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(35,'NURIINFOS',1,'정규직','SI','유지보수');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(36,'MORAN C and T',1,'정규직','SI','프론트엔드');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(37,'E3PS이쓰리피에스',2,'정규직','SP','백엔드/서버개발');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(38,'MOCOMSYS',3,'정규직','SP','안드로이드 개발');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(39,'주식회사트인기술',1,'계약직','OP','정보보안');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(40,'대교CNS',1,'계약직','OP','정보보안');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(41,'한길TIS(한국세무사회전산법인)',3,'정규직','Solution','백엔드/서버개발');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(42,'POINT-I',0,'계약직','Solution','IOS개발');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(43,'brainz',1,'정규직','SE','정보보안');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(44,'Haram-I',1,'정규직','SM','CISO');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(45,'EASYCERTI',3,'정규직','SM','웹개발');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(46,'CAFE24',2,'계약직','SE','유지보수');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(47,'한국어촌어항공단',3,'정규직','SI','웹개발');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(48,'현대일렉트릭',2,'계약직','SE','유지보수');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(49,'(주)인우기술',2,'계약직','Solution','보안컨설팅');
insert into tblEnterprise(enterprise_seq, ent_name, ent_people, ent_type, ent_sector, ent_recuit) values(50,'심네트',2,'인턴','SI','프론트엔드');
