-- tblPublisher 출판사 데이터

insert into tblPublisher(publisher_seq, name) values(1, '제이펍');
insert into tblPublisher(publisher_seq, name) values(2, '비제이퍼블릭');
insert into tblPublisher(publisher_seq, name) values(3, '길벗');
insert into tblPublisher(publisher_seq, name) values(4, '한빛미디어');
insert into tblPublisher(publisher_seq, name) values(5, '에이콘출판');
insert into tblPublisher(publisher_seq, name) values(6, '위키북스');
insert into tblPublisher(publisher_seq, name) values(7, '데브기어출판부');
insert into tblPublisher(publisher_seq, name) values(8, '생능출판');
insert into tblPublisher(publisher_seq, name) values(9, '인사이트');
insert into tblPublisher(publisher_seq, name) values(10, '영진닷컴');
insert into tblPublisher(publisher_seq, name) values(11, '골든래빗(주)');
insert into tblPublisher(publisher_seq, name) values(12, '이지스퍼블리싱');
insert into tblPublisher(publisher_seq, name) values(13, '앤써북');
insert into tblPublisher(publisher_seq, name) values(14, '디지털북스');
insert into tblPublisher(publisher_seq, name) values(15, '반니');
insert into tblPublisher(publisher_seq, name) values(16, '씨에치오 얼라이언스(CHO Alliance)');
insert into tblPublisher(publisher_seq, name) values(17, '정보문화사');
insert into tblPublisher(publisher_seq, name) values(18, '디비안(주)(DBian)');
insert into tblPublisher(publisher_seq, name) values(19, '엑셈');
insert into tblPublisher(publisher_seq, name) values(20, '한국데이터산업진흥원');
insert into tblPublisher(publisher_seq, name) values(21, '시대고시기획');
insert into tblPublisher(publisher_seq, name) values(22, '웹액츄얼리코리아');
insert into tblPublisher(publisher_seq, name) values(23, '도서출판 홍릉(홍릉과학출판사)');
insert into tblPublisher(publisher_seq, name) values(24, '현우사');
insert into tblPublisher(publisher_seq, name) values(25, '로드북');
insert into tblPublisher(publisher_seq, name) values(26, '좋은땅');
insert into tblPublisher(publisher_seq, name) values(27, '아이비김영');
insert into tblPublisher(publisher_seq, name) values(28, '21세기사');
insert into tblPublisher(publisher_seq, name) values(29, '다락원');
insert into tblPublisher(publisher_seq, name) values(30, '인포앤북');
insert into tblPublisher(publisher_seq, name) values(31, '사이버북스');
insert into tblPublisher(publisher_seq, name) values(32, '한빛아카데미');
insert into tblPublisher(publisher_seq, name) values(33, '생능북스');
