-- tblSujectName 과목명테이블 데이터

insert into tblSubjectName (subname_seq, subname, subname_subject) values(1,'Python','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(2,'C','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(3,'Java','공통');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(4,'Spring','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(5,'myBatis','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(6,'Visual Basic','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(7,'JavaScript','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(8,'html/css/jquery','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(9,'Oracle','공통');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(10,'Django','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(11,'빅데이터','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(12,'PHP','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(13,'servelt','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(14,'ajax','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(15,'sw','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(16,'Delphi/Object Pascal','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(17,'Fortran','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(18,'react','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(19,'Go','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(20,'MATLAB','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(21,'SAS','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(22,'(Visual) FoxPro','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(23,'COBOL','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(24,'Scratch','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(25,'Prolog','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(26,'Kotlin','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(27,'Rust','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(28,'PL/SQL','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(29,'Objective-C','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(30,'Ada','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(31,'Lisp','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(32,'Lua','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(33,'Scala','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(34,'VBScript','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(35,'Julia','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(36,'Logo','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(37,'Dart','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(38,'D','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(39,'ABAP','선택');
insert into tblSubjectName (subname_seq, subname, subname_subject) values(40,'PowerShell','선택');