-- tblTeachRec 교사추천도서 데이터

insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(1, 1, '비전공자를 위한 이해할 수 있는 Java  지식', '2020-03-12', 3, 1);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(2, 2, '1일 1로그 100일 완성 Java 지식', '2020-03-13', 3, 2);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(3, 3, 'Java와 40개의 작품들', '2020-03-14', 3, 3);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(4, 4, '혼자 공부하는 Java', '2020-04-01', 3, 4);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(5, 5, 'Do it! 점프 투 Java', '2020-04-02', 3, 5);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(6, 6, '문제 해결력을 높이는 알고리즘과 자료 구조', '2020-04-03', 3, 6);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(7, 7, '자료구조', '2020-04-04', 3, 7);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(8, 8, '코딩 테스트를 위한 자료 구조와 알고리즘 with Java', '2020-04-05', 3, 8);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(9, 9, '윤성우의 열혈 자료구조', '2020-05-20', 3, 9);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(10, 1, 'Oracle의 기술', '2020-05-22', 9, 11);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(11, 2, 'Java 개발과 Jindo 프레임워크', '2020-05-23', 3, 12);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(12, 3, '몰입! Java', '2020-05-24', 3, 13);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(13, 4, '고성능 Java 그래픽스', '2020-06-25', 3, 14);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(14, 5, 'Java 정규표현식', '2020-06-26', 3, 15);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(15, 6, 'Java의 모든 것!', '2020-06-27', 3, 16);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(16, 7, 'Java 이해와 AngularJS 활용', '2020-06-28', 3, 17);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(17, 8, '처음 만나는 Java', '2020-06-29', 3, 18);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(18, 9, '자바스크립트 테스트와 디버깅', '2020-07-10', 7, 19);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(19, 1, 'Spring의 모든 것!', '2020-07-12', 4, 21);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(20, 2, '리얼월드 Django', '2020-07-13', 10, 22);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(21, 3, 'Oracle 쉽게 이해하기', '2020-09-03', 9, 23);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(22, 4, 'Java 마스터하기', '2020-09-04', 3, 24);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(23, 5, 'Oracle 입문하자!', '2020-09-05', 9, 25);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(24, 6, '일래스틱 스택을 이용한 Java', '2020-11-16', 3, 26);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(25, 7, 'Java 엔지니어링', '2020-11-17', 3, 27);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(26, 8, '실전! Oracle 활용한 개발', '2020-11-18', 9, 28);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(27, 9, 'Java 탐구생활', '2021-03-17', 3, 29);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(28, 1, 'myBatis를 배워보자', '2021-04-19', 5, 31);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(29, 2, 'Django 서버리스 아키텍처', '2021-04-20', 10, 32);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(30, 3, '쉽게 배우는 PL/SQL', '2021-04-21', 28, 33);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(31, 4, 'AWS 공인 솔루션스 아키텍트 올인원 어소시에이트 and Oracle', '2021-06-19', 9, 1);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(32, 5, 'PL/SQL를 마스터하자!', '2021-06-20', 28, 2);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(33, 6, '당신이 지금 알아야 할 Java', '2021-09-21', 3, 3);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(34, 7, 'Spring의 기초', '2021-09-22', 4, 4);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(35, 8, 'Spring 레시피', '2021-09-23', 4, 5);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(36, 9, 'Oracle이 무엇인가', '2021-10-24', 9, 6);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(37, 1, '서비스 운영이 쉬워지는 Oracle 가이드', '2021-10-26', 9, 8);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(38, 2, 'Python로 배우 개발 101', '2021-11-27', 1, 9);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(39, 3, 'AWS 공인 솔루션스 아키텍트 스터디 가이드와 Java: 어소시에이트', '2021-11-28', 3, 10);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(40, 4, '그림으로 이해하는 Oracle 구조와 기술', '2022-03-29', 9, 11);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(41, 5, '스프링 부트와 AWS로 혼자 구현하는 웹 서비스', '2022-03-30', 4, 12);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(42, 6, '효율성이 배가되는 Oracle 가이드북', '2022-03-31', 9, 13);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(43, 7, '모두의 Spring', '2022-04-13', 4, 14);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(44, 8, '실습과 그림으로 배우는 Java', '2022-04-14', 3, 15);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(45, 9, 'Java 프로그래밍 완전정복', '2022-05-03', 3, 16);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(46, 1, '뇌를 자극하는 Java 프로그래밍', '2022-05-05', 3, 18);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(47, 2, '된다! Python의 모든 것!', '2022-05-06', 1, 19);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(48, 3, '처음 배우는 Oracle', '2022-05-07', 9, 20);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(49, 4, '이것이 Java다', '2022-05-08', 3, 21);
insert into tblTeachRec(book_seq, teacher_seq, rec_name, book_date, subname_seq, publisher_seq) values(50, 5, 'Spring 입문자를 위한 명령어 사전', '2022-05-09', 4, 22);
