-- tblTextBook 교재 데이터

insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(1,'Do it! 점프 투 파이썬 (파이썬 3 최신 버전 반영) 이지스퍼블리싱-Do it! 시리즈','리토 마이어',1);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(2,'혼자 공부하는 파이썬 : 파이썬 최신 버전 혼자 공부하는 시리즈','박성완',2);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(3,'비전공자도 이해할 수 있는 AI 지식 : 구글 검색부터 유튜브 추천, 파파고 번역과 내비게이션까지 일상을 움직이는 인공지능 이해하기','최일선',3);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(4,'만들면서 배우는 C과 40개의 작품들 : 자동화, 크롤링, 이미지처리, 데이터분석, 웹페이지, GUI 프로그램, 게임, 인공지능 프로그램 직접 만들며 배우기','최원효',4);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(5,'혼자 공부하는 C : 1:1 과외하듯 배우는 C 자습서 혼자 공부하는 시리즈','에릭 윈드밀',5);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(6,'구글 엔지니어는 이렇게 일한다 : 구글러가 전하는 문화, 프로세스, 도구의 모든 것 C언어편','피터 슈패스',6);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(7,'Java의 정석 : 최신 Java 8.0 포함 (3판)','블레이크 마이크',7);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(8,'혼자 공부하는 Java언어 혼자 공부하는 시리즈','김원경',8);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(9,'이것이 취업을 위한 코딩 테스트다 with Java : 취업과 이직을 결정하는 알고리즘 인터뷰 완벽 가이드, C/C++, 자바 코드 제공 한빛미디어-이것이 시리즈','김원경',9);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(10,'모던 Spring Deep Dive : Spring의 기본 개념과 동작 원리 위키북스 프로그래밍 , 프랙티스 시리즈 026','천인국',10);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(11,'쏙쏙 들어오는 Spring 코딩 : 심플한 코드로 복잡한 소프트웨어 길들이기','김태호',11);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(12,'한 권으로 읽는 Spring : 더 나은 소프트웨어 개발을 위한 하드웨어, 자료구조, 필수 알고리즘 등 프로그래머의 비밀 노트','벨렌 크루즈 파타',12);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(13,'myBatis : 14가지 GoF 필살 패턴! 유지 관리가 편리한 myBatis를 만드는 법','실뱅 라타부이',13);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(14,'일잘러의 비밀, 엑셀 대신 myBatis로 업무 자동화하기 : 엑셀 반복 업무로 지친 직장인, myBatis으로 칼퇴하자! 일잘러의 비밀 시리즈','조상철',14);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(15,'윤성우의 열혈 myBatis 프로그래밍 (개정판, 부록 : 동영상 강의) ','조상철',15);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(16,'이펙티브 Visual Basic Effective Visual Basic 3/E','홍정아',16);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(17,'Visual Basic 개발 시작하기 : DDD 핵심 개념 정리부터 구현까지','오준석',17);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(18,'객체지향의 사실과 오해 : 역할, 책임, 협력 관점에서 본 객체지향 위키북스 IT Leaders 시리즈 023 : Visual Basic','정재곤',18);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(19,'프로그래머의 뇌 : 훌륭한 프로그래머가 알아야 할 인지과학의 모든 것 : JavaScript편','고돈호',19);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(20,'혼자 공부하는 얄팍한 코딩 지식 : 비전공자도 1:1 과외하듯 배우는 IT 지식 입문서 혼자 공부하는 시리즈 : JavaScript편','강성윤',20);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(21,'윤성우의 열혈 JavaScript 프로그래밍 (개정판, 부록 : 동영상 강의) ','오가와 유타로',21);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(22,'혼자 공부하는 html/css/jquery 혼자 공부하는 시리즈','서민우',22);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(23,'이득우의 html/css/jquery : 39가지 예제로 배운다! html/css/jquery를 구성하는 html/css/jquery의 모든 것','퀀티랩',23);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(24,'Do it! html/css/jquery 편 : html/css/jquery 강의 5년의 합격 노하우, 역대 기출 문제 총망라! 이지스퍼블리싱-Do it! 시리즈','디파니안 사르카르',24);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(25,'Oracle : Oracle 데이터 예제 프로젝트로 배우는 전자정부 표준 Oracle 시리즈','윤준호',25);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(26,'Oracle 자율학습 : 기초부터 반응형 웹까지 초보자를 위한 Oracle 입문서 ','박상길',26);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(27,'Oracle  완벽 가이드 : 다양한 예제와 함께 기초부터 최신 기법까지 배우는 (개정2판) 위키북스- 데이터 사이언스 시리즈 081','바라스 람순다르',27);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(28,'Django를 다루는 기술','김성진',28);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(29,'모두의 Django : 누구나 쉽게 이해하는 Django (개정3판,동영상 강의,별책(책속의 책/84쪽))','조경래',29);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(30,'밑바닥부터 시작하는 Django : 파이썬으로 익히는 Django 이론과 구현','딥러닝호형',30);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(31,'빅데이터의 정석 기초편','사이토 고키',31);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(32,'빅데이터의 교과서 : 기본기에 충실한 빅데이터 14 입문서 (개정2판)','서지영',32);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(33,'핸즈온 빅데이터 : 사이킷런, 케라스, 텐서플로 2를 활용한 빅데이터, 딥러닝 완벽 실무 (2판, 전면 컬러판)','사이토 고키',33);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(34,'Must Have PHP·PHP 문제해결 전략 : 캐글 수상작 리팩터링으로 배우는 문제해결 프로세스와 전략 골든래빗 - Must Have 시리즈','신백균',10);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(35,'PHP 인터뷰 : 95가지 PHP 문제 풀이로 완성하는 코딩 테스트 (2021 세종도서 학술부문 우수도서 선정) ','조태호',11);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(36,'Do it! 지옥에서 온 문서 관리자 PHP 입문 : 생활코딩 지옥에서 온 PHP 강의 52개 엄선, 기초와 필수 기능을 모두 담았다! 이지스퍼블리싱-Do it! 시리즈','씨에치오 얼라이언스 편집부',12);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(37,'Do it! 자료구조와 함께 배우는 Servelt 입문 : Servelt 편 이지스퍼블리싱-Do it! 시리즈','이경택',13);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(38,'Servelt 한권으로 끝내기 : Servelt 실기대비','프랑소와 숄레',14);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(39,'쉽고 빠른 Servelt 앱 개발 : Servelt로 화면 구현·상태 관리·데이터 처리·디자인 패턴 익히기','사이토 고키',15);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(40,'Do it! ajax 만들기 입문 : 코딩 몰라도 OK!','박해선',16);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(41,'프로페셔널 ajax','유일환',17);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(42,'열혈코딩: ajax로 만나는 ajax','정희락',18);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(43,'SW 앱 개발에 딱 맞는 플러터와 다트 입문','린 베일리',19);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(44,'모두의 SW','빌 카윈',20);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(45,'SW 인 액션','사카시타 유리',21);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(46,'Delphi/Object Pascal 프로그래밍','벤 포터',22);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(47,'인사이드 Delphi/Object Pascal','이경오',23);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(48,'Delphi/Object Pascal with 델파이 2편: 고급활용','미크',24);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(49,'Fortran with 델파이 1편: 기초다지기','김도연',25);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(50,'그림으로 쉽게 설명하는 Fortran','유연수',26);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(51,'커니의 Fortran: 차세대 Fortran 개발자를 위한','앤서니 몰리나로',27);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(52,'React Application Development(한국어판)','가사키 나가토',28);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(53,'React 프로그래밍','김성식',29);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(54,'돈 되는 React 앱 만들기','아사이 아츠시',30);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(55,'Go를 활용한 실전 앱 만들기','임호진',31);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(56,'Joyce의 Go 앱 프로그래밍 with Go','조시형',32);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(57,'오준석의 Go 생존코딩: Go 편','한국데이터산업진흥원',33);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(58,'Do it! MATLAB 앱 프로그래밍','정미나',1);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(59,'이것이 MATLAB with MATLAB','우재남',2);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(60,'Do it! 깡샘의 MATLAB 앱 프로그래밍 with MATLAB','한국데이터진흥원',3);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(61,'만들면서 배우는 SAS','매트 마키스',4);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(62,'SAS 직접 코딩하기 with 라즈베리파이 피코','원철연',5);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(63,'SAS 이용한 주식투자','이브 포셀로',6);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(64,'FoxPro를 활용한 학습','조 모건',7);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(65,'비전공자를 위한 FoxPro','정승호',8);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(66,'비전공자도 이해할 수 있는 FoxPro','Eroc Traub',9);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(67,'생명과학을 위한 COBOL','조나단 웩슬러',10);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(68,'케라스로 구현하는 COBOL','자비에르 보우리',11);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(69,'COBOL 챗봇','장수진',12);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(70,'Scratch을 위한 Scratch 입문','안토 아라빈스',13);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(71,'밑바닥부터 시작하는 Scratch 3','Yoshinao Mori',14);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(72,'Scratch 교과서','니꼴라스',15);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(73,'밑바닥부터 시작하는 Prolog 2','애덤 프리먼',16);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(74,'Prolog 문제해결 전략','더글러스 크락포드',17);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(75,'모두의 Prolog','이재승',18);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(76,'미국 연구개발 테마 총서 Vol 5: Kotlin(2020)','조현영',19);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(77,'Kotlin 개발자','어포스트',20);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(78,'케라스 창시자에게 배우는 Kotlin','이웅모',21);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(79,'밑바닥부터 시작하는 Rust','이케다 야스노부',22);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(80,'혼자 공부하는 Rust','이은정',23);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(81,'Rust 알기!','윤인성',24);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(82,'불친절한 PL/SQL 프로그래밍','애덤 스콧',25);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(83,'HEAD FIRST PL/SQL','박경배',26);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(84,'PL/SQL AntiPatterns','페르난도 돌리오',27);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(85,'그림으로 배우는 Objective-C 입문','마레인 하버비케',28);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(86,'손에 잡히는 10분 Objective-C','이선 브라운',29);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(87,'이경오의 Objective-C 비밀노트','알베르토 몬탈레시',30);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(88,'Ada 레벨업','고승원',31);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(89,'모두의 Ada','댄 밴더캄',32);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(90,'초보자를 위한 Ada 200제','김정헌',33);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(91,'Lisp 쿡북','조현영',1);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(92,'데이터 분석을 위한 Lisp 레시피','곽문기',2);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(93,'Lisp 튜닝 가이드','야코프 페인',3);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(94,'Lua 첫걸음','니꼴라스',4);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(95,'이기적 Lua 개발자 이론서+기출문제(2021)','주홍철',5);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(96,'친절한 Lua 튜닝','박민경',6);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(97,'Scala 전문가 가이드','고경희',7);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(98,'2022 유선배 Scala개발자 과외노트','황재호',8);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(99,'혼자 공부하는 Scala','이길배',9);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(100,'VBScript 자격검정 실전문제','카이 호스트만',10);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(101,'웹디자이너를 위한 VBScript','고승원',11);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(102,'예제로 배우는 VBScript','고승원',12);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(103,'웹 앱 API 개발을 위한 Julia','윤인성',13);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(104,'Julia 코딩의 기술','황기태',14);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(105,'맛있는 Julia','반병현',15);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(106,'Logo 코딩','데이비드 플래너건',16);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(107,'Logo로 프로그래밍 시작하기','이고잉',17);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(108,'Logo 인 더 브라우저','김기수',18);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(109,'Dart 가자!','권영재',19);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(110,'Dart 입문','니꼴라스',20);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(111,'백견불여일타 Dart 입문','리토 마이어',21);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(112,'Do it! 클론 코딩 영화 평점 웹서비스 : D','박성완',22);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(113,'D 16','최일선',23);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(114,'D는 왜 그 모양일까?','최원효',24);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(115,'실전 ABAP 프로그래밍','에릭 윈드밀',25);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(116,'ABAP 교과서','피터 슈패스',26);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(117,'ABAP 파워북','블레이크 마이크',27);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(118,'모던 PowerShell Deep Dive','김원경',28);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(119,'PowerShell 코드 레시피 278','김원경',29);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(120,'Lets 실전 예제로 배우는 PowerShell','천인국',30);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(121,'혼자 공부하는 자바스크립트','김태호',31);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(122,'모던 자바스크립트 Deep Dive','벨렌 크루즈 파타',32);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(123,'자바스크립트는 모든 곳에 존재한다','실뱅 라타부이',33);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(124,'HTML5 중심의 CSS3와 자바스크립트','조상철',1);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(125,'디노 첫걸음','조상철',2);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(126,'자바스크립트 스킬업','홍정아',3);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(127,'한 권으로 끝내는 Node , Express','오준석',4);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(128,'모던 자바스크립트 핵심 가이드','정재곤',5);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(129,'Vue.js 프로젝트 투입 일주일 전','고돈호',6);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(130,'이펙티브 타입스크립트','강성윤',7);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(131,'스무디 한 잔 마시며 끝내는 리액트+TDD','오가와 유타로',8);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(132,'Let’s Get IT 자바스크립트 프로그래밍','서민우',9);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(133,'오늘부터 자바스크립트','퀀티랩',10);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(134,'단숨에 배우는 타입스크립트','디파니안 사르카르',11);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(135,'Do it! 클론 코딩 트위터','윤준호',12);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(136,'실시간 모니터링 시스템을 만들며 정복하는 MEVN','박상길',13);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(137,'Node.js로 서버 만들기','바라스 람순다르',14);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(138,'Do it! 자바스크립트 입문','김성진',15);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(139,'자바스크립트 + 제이쿼리 입문','조경래',16);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(140,'인터랙션디자인을 위한 Java Script','딥러닝호형',17);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(141,'무던한 개발자를 위한 모던한 자바스크립트','사이토 고키',18);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(142,'바닐라 자바스크립트','서지영',19);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(143,'Node.js 프로젝트 투입 일주일 전','사이토 고키',20);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(144,'자바스크립트 프로그래밍 입문','신백균',21);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(145,'명품 HTML5+CSS3+Javascript 웹 프로그래밍','조태호',22);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(146,'코딩만 따라 해도 웹페이지가 만들어지는 HTML+CSS+자바스크립트','씨에치오 얼라이언스 편집부',23);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(147,'자바스크립트 완벽 가이드','이경택',24);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(148,'생활코딩! HTML+CSS+자바스크립트','프랑소와 숄레',25);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(149,'코딩 자율학습 HTML + CSS + 자바스크립트','사이토 고키',26);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(150,'코로나보드로 배우는 실전 웹 서비스 개발','박해선',27);
insert into tblTextBook (txtbook_seq,  name, author, publisher_seq) values(151,'Do it! 클론 코딩 줌','유일환',28);