insert into z_actor values (1	,'댄 포글러');
insert into z_actor values (2	,'매즈 미켈슨');
insert into z_actor values (3	,'에디 레드메인');
insert into z_actor values (4	,'주드 로');
insert into z_actor values (5	,'김상경');
insert into z_actor values (6	,'김정태');
insert into z_actor values (7	,'이선빈');
insert into z_actor values (8	,'장혁진');
insert into z_actor values (9	,'레이첼 맥아담스');
insert into z_actor values (10	,'베네딕트 웡');
insert into z_actor values (11	,'엘리자베스 올슨');
insert into z_actor values (12	,'오달수');
insert into z_actor values (13	,'천우희');
insert into z_actor values (14	,'박지현');
insert into z_actor values (15	,'신하균');
insert into z_actor values (16	,'차래형');
insert into z_actor values (17	,'다니엘 래드클리프');
insert into z_actor values (18	,'산드라 블록');
insert into z_actor values (19	,'채닝 테이텀');
insert into z_actor values (20	,'마동석' );
insert into z_actor values (21	,'박지환');
insert into z_actor values (22	,'손석구');
insert into z_actor values (23	,'허동원');
insert into z_actor values (24	,'손숙');
insert into z_actor values (25	,'정석용');
insert into z_actor values (26	,'김도윤');
insert into z_actor values (27	,'봉재현');
insert into z_actor values (28	,'서지수');
insert into z_actor values (29	,'설아');
insert into z_actor values (30	,'윤진영');
insert into z_actor values (31	,'이시원');
insert into z_actor values (32	,'이호철');
insert into z_actor values (33	,'최귀화');
insert into z_actor values (34	,'마크 월버그');
insert into z_actor values (35	,'소피아 테일러 알리');
insert into z_actor values (36	,'타티 가브리엘');
insert into z_actor values (37	,'손호준');
insert into z_actor values (38	,'이규형');
insert into z_actor values (39	,'이중옥');
insert into z_actor values (40	,'전노민');
insert into z_actor values (41	,'김갑수');
insert into z_actor values (42	,'정우');
insert into z_actor values (43	,'지승현');
insert into z_actor values (44	,'최무성');
insert into z_actor values (45	,'길리언 제이콥스');
insert into z_actor values (46	,'벤 포스터');
insert into z_actor values (47	,'크리스 파인');
insert into z_actor values (48	,'키퍼 서덜랜드');
insert into z_actor values (49	,'야히아 압둘 마틴 2세');
insert into z_actor values (50	,'에이사 곤잘레스');
insert into z_actor values (51	,'제이크 질렌할');
insert into z_actor values (52	,'김혜윤');
insert into z_actor values (53	,'박혁권');
insert into z_actor values (54	,'이휘종');
insert into z_actor values (55	,'최희진');
insert into z_actor values (56	,'벤 슈와츠');
insert into z_actor values (57	,'이드리스 엘바');
insert into z_actor values (58	,'제임스 마스던');
insert into z_actor values (59	,'짐 캐리');
insert into z_actor values (60	,'김연우');
insert into z_actor values (61	,'마츠오카 요시츠구');
insert into z_actor values (62	,'시모노 히로');
insert into z_actor values (63	,'이경태');
insert into z_actor values (64	,'마크 마론');
insert into z_actor values (65	,'샘 록웰');
insert into z_actor values (66	,'안소니 라모스');
insert into z_actor values (67	,'크레이그 로빈슨');
insert into z_actor values (68	,'로버트 패틴슨');
insert into z_actor values (69	,'제프리 라이트');
insert into z_actor values (70	,'콜린 파렐');
insert into z_actor values (71	,'폴 다노');
insert into z_actor values (72	,'금성무');
insert into z_actor values (73	,'양조위');
insert into z_actor values (74	,'왕페이');
insert into z_actor values (75	,'임청하');
insert into z_actor values (76	,'박해일');
insert into z_actor values (77	,'변요한');
insert into z_actor values (78	,'손현주');
insert into z_actor values (79	,'안성기');
insert into z_actor values (80	,'강동원');
insert into z_actor values (81	,'배두나');
insert into z_actor values (82	,'송강호');
insert into z_actor values (83	,'아이유');
insert into z_actor values (84	,'오가타 메구미');
insert into z_actor values (85	,'우치야마 코우키');
insert into z_actor values (86	,'코마츠 미카코');
insert into z_actor values (87	,'하나자와 카나');
insert into z_actor values (88	,'아드리아 아르호나');
insert into z_actor values (89	,'알 마드리걸');
insert into z_actor values (90	,'자레드 레토');
insert into z_actor values (91	,'자레드 해리스');
insert into z_actor values (92	,'박기덕');
insert into z_actor values (93	,'오종혁');
insert into z_actor values (94	,'이한휘');
insert into z_actor values (95	,'정의욱');
insert into z_actor values (96	,'기은수');
insert into z_actor values (97	,'문서별');
insert into z_actor values (98	,'서범석');
insert into z_actor values (99	,'황장준');
insert into z_actor values (100	,'산드라 오');
insert into z_actor values (101	,'피벨 스튜어트');
insert into z_actor values (102	,'김동휘');
insert into z_actor values (103	,'박병은');
insert into z_actor values (104	,'박해준');
insert into z_actor values (105	,'최민식');
insert into z_actor values (106	,'베네딕트 컴버배치');
insert into z_actor values (107	,'젠데이아 콜먼');
insert into z_actor values (108	,'존 파브로');
insert into z_actor values (109	,'톰 홀랜드');
insert into z_actor values (110	,'드완다 와이즈');
insert into z_actor values (111	,'로라 던');
insert into z_actor values (112	,'브라이스 달라스 하워드');
insert into z_actor values (113	,'크리스 프랫');
insert into z_actor values (114	,'나탈리 포트만');
insert into z_actor values (115	,'크리스 헴스워스');
insert into z_actor values (116	,'테사 톰슨');
insert into z_actor values (117	,'유민곤');
insert into z_actor values (118	,'이봄');
insert into z_actor values (119	,'이태경');
insert into z_actor values (120	,'이한주');
insert into z_actor values (121	,'김소희');
insert into z_actor values (122	,'김용');
insert into z_actor values (123	,'김한나');
insert into z_actor values (124	,'최정현');
insert into z_actor values (125	,'나카지마 아유무');
insert into z_actor values (126	,'모리 카츠키');
insert into z_actor values (127	,'현리');
insert into z_actor values (128	,'후루카와 코토네');
insert into z_actor values (129	,'비비 렉사');
insert into z_actor values (130	,'커비 하월 바티스트');
insert into z_actor values (131	,'크리스틴 벨');
insert into z_actor values (132	,'폴 월터 하우저');
insert into z_actor values (133	,'박해수');
insert into z_actor values (134	,'설경구');
insert into z_actor values (135	,'양동근');
insert into z_actor values (136	,'이엘');
insert into z_actor values (137	,'김민희');
insert into z_actor values (138	,'박미소');
insert into z_actor values (139	,'서영화');
insert into z_actor values (140	,'이혜영');
insert into z_actor values (141	,'매튜 맥퍼딘');
insert into z_actor values (142	,'켈리 맥도날드');
insert into z_actor values (143	,'콜린 퍼스');
insert into z_actor values (144	,'말루마');
insert into z_actor values (145	,'오웬 윌슨');
insert into z_actor values (146	,'제니퍼 로페즈');
insert into z_actor values (147	,'숀 애쉬모어');
insert into z_actor values (148	,'마이클 페나');
insert into z_actor values (149	,'존 브래들리');
insert into z_actor values (150	,'패트릭 윌슨');
insert into z_actor values (151	,'할리 베리');
insert into z_actor values (152	,'발 킬머');
insert into z_actor values (153	,'에드 해리스');
insert into z_actor values (154	,'제니퍼 코넬리');
insert into z_actor values (155	,'톰 크루즈');
insert into z_actor values (156	,'나오미 왓츠');
insert into z_actor values (157	,'엘렌 데이빗');
insert into z_actor values (158	,'유연석');
insert into z_actor values (159	,'찰리 히튼');
insert into z_actor values (160	,'크리스탈 밸린트');
insert into z_actor values (161	,'올가 쿠릴렌코');
insert into z_actor values (162	,'이승준');
insert into z_actor values (163	,'네다 마르그레테 라바');
insert into z_actor values (164	,'서지오 파블로스');
insert into z_actor values (165	,'제이슨 슈왈츠먼');
insert into z_actor values (166	,'J.K. 시몬스');
insert into z_actor values (167	,'사말 예슬라모바');
insert into z_actor values (168	,'아스카르 일리아소브');
insert into z_actor values (169	,'이고르 사보치킨');
insert into z_actor values (170	,'문소리');

select * from z_actor;