insert into z_review values (1, 1, 'choi****', 'Y', 6, 437, '진짜 해리포터와 덤블도어랑의 의리로 봄 +영상미랑 CG는 괜찮은데..스토리는 너무 기대하지 마시길 중간에 호그와트 나올때 찡하긴함');
insert into z_review values (2, 1, 'ldkp****', 'Y', 6, 360, '이 시리즈의 끝을 꼭 봐야겠어');
insert into z_review values (3, 1, 'awak****', 'N', 5, 11, '신비한 동물들 때문에 5점 준다. 영화자체는 엉망인 수준.');
insert into z_review values (4, 2, 'kmyu****', 'N', 10, 246, '가습기살균제 피해자 입니다. 사람들의 기억에서 사라지는 사건이었는데 소재원 작가님은 포기하지');
insert into z_review values (5, 2, 'hong****', 'Y', 8, 42, '너무 무겁지않을까했는데 좋은 영화였습니다.');
insert into z_review values (6, 2, 'silv****', 'Y', 10, 72, '많은 사람들이 알아야하는 영화');
insert into z_review values (10, 4, '123j****', 'Y', 10, 117, '하…기가 막힌다 진짜…무서운 점은….');
insert into z_review values (11, 4, 'full****', 'N', 7, 16, '나이가 들수록 가해자에 대한 분노보다 피해자의 아픔이 더 가슴이 박힌다');
insert into z_review values (12, 4, 'gp14****', 'Y', 8, 50, '현실적으로 잘 만든 영화');
insert into z_review values (13, 5, 'pu4n****', 'Y', 7, 78, '해리가 앵커를 만났을 때');
insert into z_review values (14, 5, 'cvac****', 'Y', 8, 49, '나름 좋은 반전. 예상치 못하면 잼나다');
insert into z_review values (15, 5, 'twic****', 'N', 10, 22, '시사회로 먼저봤음 천우희 연기 오랜만에 봤는데 역시 잘하고 이해영 배우님 연기가');
insert into z_review values (16, 6, 'milk****', 'Y', 4, 31, '이 영화의 진미는 영화를 다 보고나서 웃긴다는 것이다.');
insert into z_review values (17, 6, 'smy1****', 'Y', 2, 20, '최고의캐스팅으로 빗어낸 찰흙덩어리');
insert into z_review values (18, 6, 'robo****', 'N', 8, 2, '킬링타임용으로 즐기기 딱 좋은 오락영화');
insert into z_review values (22, 8, 'wttr****', 'N', 10, 21, '손현주 연기 진짜.. 진짜 너무 잘한다');
insert into z_review values (23, 8, 'meta****', 'Y', 8, 9, '신파스러운 전개를 최대한 배제하고, 과도한 설명 없이 보여줄 것은 확실히 보여준다. (영화적 사건이 없다는 말은 아님)');
insert into z_review values (24, 8, 'grtb****', 'Y', 8, 4, '무식하고 철없고 무뚝뚝한 애새키어른 ㅋㅋ');
insert into z_review values (28, 10, 'toto****', 'N', 8, 7, '저예산 독립영화치고 재미있게 봤네요 ㅋ스토리도 나름 웃김.. 이거만든 감독 세계관이 보이는듯 ㅋ 아무생각없이 보기 딱 좋음');
insert into z_review values (29, 10, 'wook****', 'N', 10, 6, '호불호가 있을 것 같은데 저는 넘 재밌게 봤어요.마지막 장면에서는 순간 바닐라스카이가 떠올랐네요.');
insert into z_review values (30, 10, 'raie****', 'N', 2, 13, '유구무언…할말하않');
insert into z_review values (31, 11, 'kimj****', 'Y', 7, 574, '해적3 - 바다로 간 피터파커');
insert into z_review values (32, 11, 'supe****', 'Y', 5, 41, '예상가능해서 유치하게 느껴지는 어드벤쳐물. 왠지모르게 피터파커의 부업 활동처럼 느껴진다.');
insert into z_review values (33, 11, 'jeje****', 'Y', 8, 124, '톰 홀랜드가 출연했던 여느 마블 작품들처럼 탄성이 자아내질 만큼 화려하진 않았지만, 충분히 눈길을 사로잡는 비주얼과 액션 덕에 흥미진진한 116분을 보낼 수 있었다.');
insert into z_review values (34, 12, 'byka****', 'Y', 2, 168, '이거 클레멘타인 급인가요?');
insert into z_review values (35, 12, 'dhjh****', 'Y', 1, 88, '재미없는영화만 평 남기는데 이 영화가 그영화네');
insert into z_review values (36, 12, '6550****', 'N', 1, 5, '이런쓰레기 처음봤어요 50분버티다가 결국 도중에나옴');
insert into z_review values (37, 13, 'euna****', 'Y', 2, 413, '한국영화도 자막 달아야 됨');
insert into z_review values (38, 13, 'juri****', 'Y', 7, 87, '부산사투리 대화 내용이 부산사람 아니면 알아듣기 어렵게 웅얼웅얼 들리는 거는 단점. 연기력은 볼만함. 내용은 조폭영화가 조폭영화임.');
insert into z_review values (39, 13, 'pann****', 'Y', 10, 67, '장난 아니고 리얼 역대급입니다.남자분들 가슴 뜨거워지는 거 장담합니다.');
insert into z_review values (40, 14, 'supe****', 'N', 8, 6, '크리스 파인이 연기를 이렇게 잘하는 줄 몰랐음. 내용이고 액션이고 따지지말고 크리스 파인을 위해 한번쯤 볼만한 영화');
insert into z_review values (41, 14, 'dltm****', 'Y', 7, 6, '킬링타임용으로 괜찮아요~!');
insert into z_review values (42, 14, 'soal****', 'N', 5, 3, '내 무릎이 다 아프다...');
insert into z_review values (43, 15, 'lexp****', 'Y', 1, 68, '억지 설정과 작위적인 스토리, 지루한 카체이싱과 앰뷸런스 속 상황 묘사 및 대화. 가장 어이없는 건 범죄와 범죄자를 옹호하는 듯한 주제와 메시지네요.');
insert into z_review values (44, 15, 'beat****', 'Y', 7, 45, '별다른 스토리 없고 그냥 막 흔들어재낌');
insert into z_review values (45, 15, 'sarr****', 'N', 8, 22, '시원시원하게 터뜨리는게 화면 크고 사운드 좋은 극장에서 보기 딱 좋은 영환데 가격이 많이 올라서 선뜻 추천하기가..');
insert into z_review values (46, 16, 'i2kr****', 'Y', 8, 48, '김혜윤 연기가 불도저급');
insert into z_review values (47, 16, '93st****', 'N', 10, 42, '간만에 본 몰입감 높은 영화! 김혜윤 배우의 연기가 굉장히 인상적이었다 영화내내 극을 이끌어가는 힘이 엄청났음ㅇㅇ추천');
insert into z_review values (48, 16, 'aaat****', 'Y', 7, 33, '김혜윤의 열연이 돋보이는 영화');
insert into z_review values (49, 17, 'alal****', 'Y', 10, 42, '이거 소닉팬이면 무조건보세요');
insert into z_review values (50, 17, 'blac****', 'Y', 10, 27, '스피드 있게 처리되는 소닉과 친구들 우정');
insert into z_review values (51, 17, 'gusr****', 'Y', 10, 20, 'do u know the way?');
insert into z_review values (52, 18, 'tmdw****', 'Y', 10, 2980, '와 이거 안보면 인생 절반 후회한겁니다 여러분');
insert into z_review values (53, 18, '2son****', 'Y', 10, 1164, '작화, 영상미, 스토리 모두 최고였어요 전투씬은 진짜 역대급이였습니다.');
insert into z_review values (54, 18, 'poke****', 'Y', 1, 69, '사회악 영화 빨리 망해라');
insert into z_review values (58, 20, 'hyoj****', 'Y', 10, 1078, '원래 dc가 detective comics의 준말임. 이거에 가장 부합하는 영화인 거 같음.');
insert into z_review values (59, 20, 'xkaw****', 'Y', 4, 315, '재미없는 교수가 쉬지않고 수업을 하는 느낌.긴장감을 조성하는 효과음과 굼뜬 움직임들이 끊임없이 나와 나중에는 화가 치밀 정도');
insert into z_review values (60, 20, 'hatr****', 'N', 9, 30, '여기서 별절 낮게 다는 사람은 취향에 안맞는 것 뿐입니다. 절대 못 만든 영화가 아니니 취향 맞겠다 싶으면 보시면 됩니다. 참고로 히어로물 아닙니다.');
insert into z_review values (61, 21, 'nwhg****', 'N', 10, 935, '오늘 이영화를 본 난 영화에는 유통기한이 없다는걸 깨달았다');
insert into z_review values (62, 21, 'sobb****', 'N', 8, 673, '좋아하는 여자가 좋아하는 영화');
insert into z_review values (63, 21, 'naga****', 'Y', 10, 137, '그시절 홍콩으로 갈 수 있는 유일한 타임머신..');
insert into z_review values (70, 24, 'bail****', 'Y', 7, 193, '이건 내 지론인데, 사랑만큼 왜곡된 저주는 없을 거야.');
insert into z_review values (71, 24, 'yeon****', 'Y', 9, 10, '엔딩 OST랑 액션이 정말 좋음');
insert into z_review values (72, 24, 'shak****', 'Y', 10, 15, '이건 그냥 안 보는 사람이 손해');
insert into z_review values (73, 25, 'jsa3****', 'Y', 8, 388, '평론가 평점 못믿겠다 솔직히 베놈2보다 재밌었음쿠키영상 2개도');
insert into z_review values (74, 25, 'cpli****', 'N', 10, 145, '자레드 레토 진짜...빌런이었다가 히어로였다가 캐릭터 자체도 매력적인데 연기는 또 왤케 완벽합니까...');
insert into z_review values (75, 25, 'mspa****', 'Y', 2, 69, '소니는 마블영화 그만 만들어야');
insert into z_review values (76, 26, 'vita****', 'N', 7, 9, '오랜만에 보는 홍콩영화 동성간의 사랑을 주제로 미묘한 감정을 잘 표현한 영상미 아름다운 작품입니다.');
insert into z_review values (77, 26, 'supe****', 'Y', 6, 5, '제는 가슴 한 켠에 묻고 싶어지는 첫사랑 이야기');
insert into z_review values (78, 26, 'dudv****', 'N', 10, 2, '클리셰 범벅이지만 재밌다 영화에서만이라도 퀴어들이 어떠한 고난과 역경없이 그냥 하하호호 행복했으면 좋겠다 이미 우리 삶은 충분히 힘드니까');
insert into z_review values (79, 27, 'mjy9****', 'Y', 10, 15, '평캐다짐하게 만들어주는 영화');
insert into z_review values (80, 27, 'lucy****', 'N', 10, 1, 'ZERO(HERO) 로 타투하겠다는 거 친구가 간신히 뜯어말림');
insert into z_review values (81, 27, 'zoop****', 'Y', 10, 9, '그냥 평생 캐럿하기로 오늘도 다짐하고... 바로 2회차 예약 세븐틴 캐럿 늘 함께 걷자');
insert into z_review values (82, 28, '1gug****', 'N', 1, 7, '포스터봐 ㅋㅋ ppt로 만든 줄');
insert into z_review values (83, 28, 'sphp****', 'Y', 10, 2, '독립영화라고해서 기대안하고 봤다가 완전 만족만족! 배우들 눈빛연기 뭐야뭐야~~~영상미와 OST도 인상적인 영화!');
insert into z_review values (84, 28, 'owne****', 'N', 10, 9, '2022년 영화 공식 포스터 맞나요?');
insert into z_review values (85, 29, 'kii1****', 'N', 10, 0, 'K-조커');
insert into z_review values (86, 29, 'jkwh****', 'N', 10, 1, '영화를 보고있는네네 배우 기은수(영희)를 보고있자면 나도 모르게미소짓게 되는 영화');
insert into z_review values (87, 29, 'zmhu****', 'N', 10, 1, '여주인공 진심 이쁘네요 크게 될듯~');
insert into z_review values (91, 31, 'miss****', 'Y', 7, 192, '초반엔 상당히 신선했는데 말이죠... 리학성의 사연이 드러나면서 부터는 뻔한 결말로 치닫습니다. 급조한듯한 결말. 그래도 감동으로 잘 보고 왔어요.');
insert into z_review values (92, 31, 'jozb****', 'Y', 6, 141, '학교가 가르쳐야 할 것은 공식이 아니라 사람이다.');
insert into z_review values (93, 31, 'esso****', 'Y', 10, 318, '최민식이 열고 최민식이 닫았다....');
insert into z_review values (94, 32, 'seoh****', 'Y', 10, 100011, '삼십 대의 내가 십 대, 이십 대의 나를 만났다');
insert into z_review values (95, 32, 'kwan****', 'Y', 10, 4902, '스파이더맨 1 부터 본 사람이면 재미없을 수가 없다');
insert into z_review values (96, 32, 'nywb****', 'Y', 8, 1866, '계속 잔상처럼 남아있는 앤드류가 떨어지는 MJ를 구하고 나서 눈물 맺힌 눈');
insert into z_review values (103, 35, 'acjw****', 'N', 6, 2, '예고편에 비해 본편이 아쉽고 여주인공 연기는 인상적이었지만 남주인공은 아쉽다는 느낌.특히 화났을때의 표정과 대사톤이 많이 과장되고 불안해 어색함');
insert into z_review values (104, 35, 'ally****', 'N', 10, 1, '다큐인가 영화인가, 영진의 앞날에 평평함만 있기를');
insert into z_review values (105, 35, 'gold****', 'Y', 6, 0, '기대가 너무 컷는지는 몰라도, "그만두면 그마저도 망할 게 두려운 어설픈 인생"에 관한 한, 딱히 그럴 듯하고 기깔나는 이야기는 아니었던 것 같다.');
insert into z_review values (106, 36, 'baks****', 'N', 6, 2, '몬스터 대학교와는 전혀 다른 작품이다');
insert into z_review values (107, 36, 'gdhj****', 'N', 2, 0, '영화가 초등아래로는 어려울영화임중간에 나가는 사람많음...재미포인트가 전혀없음');
insert into z_review values (108, 36, 'kang****', 'N', 10, 2, '알록달록 너무 재미있었어요! 조카 보여주러 간 건데 저도 재미있게 봤습니다!');
insert into z_review values (112, 38, 'kimj****', 'Y', 7, 16, '4월 문화의날 올데이 5천원으로 잘봤습니다.쿠폰 주제의 영화이므로 정가로 관람하지 마세요.');
insert into z_review values (113, 38, 'newc****', 'Y', 7, 2, '실화라니 놀랍다 ㄴㅋㅋ');
insert into z_review values (114, 38, 'hogu****', 'N', 7, 1, '생각보다 나쁘지 않다. 가볍게 즐기기 좋다. 적당히 웃기고 억지스러운 부분이 기억나지않는다.');
insert into z_review values (115, 39, 'jnhn****', 'N', 1, 259, '최악입니다 시간아까우니 보지마세요 가오가 몸을 지배한 사람들이 가오만잡다가 끝남');
insert into z_review values (116, 39, 'gumi****', 'N', 1, 195, '이딴 종북영화는 망하는게 답 . 현실에서 미사일 쏴대고 어그로끄는건 북한인데 왜 일본이 악역임?? ㅋㅋ 중국 쇼트트랙 영화 욕할거없다');
insert into z_review values (117, 39, 'edc1****', 'N', 10, 431, '여기 댓글 평점이 왜 극과 극으로 나오냐면, 국내 친일파 처단하는 내용이라서 평점테러 알바 풀었음. ㅋㅋㅋㅋ');
insert into z_review values (118, 40, 'twin****', 'N', 10, 8, '이 영화 제목그대로 거품입니다.');
insert into z_review values (119, 40, 'stw7****', 'N', 4, 5, '작화랑 연출은 괜찮은데 스토리가 너무 진부합니다');
insert into z_review values (120, 40, 'xari****', 'N', 8, 1, '이 정도 영상미에 좋은스토리를 원하기엔 욕심일것같다 영상미 ost로 충분합니다.');
insert into z_review values (121, 41, 'yclo****', 'Y', 8, 24, '홍상수감독이 하고픈말? 아깝긴 뭐가 아까워. 초등학생도 아닌데. 다큰 성인이 자기 인생사는데. 상업영화찍으며 돈벌면 안 아까운가?');
insert into z_review values (122, 41, 'lami****', 'Y', 8, 12, '이혜영님 연기가 찐으로 중견 작가님들 그 자체임 이 시대의 리얼리즘');
insert into z_review values (123, 41, 'mart****', 'Y', 7, 7, '극단으로 치닫는 어색하고 불편한 분위기 속 자기고백...');
insert into z_review values (127, 43, 'cold****', 'Y', 10, 9, '너무 재밌음 눈과 귀기 즐거운 로코의 정석');
insert into z_review values (128, 43, 'love****', 'Y', 5, 3, '로코드라마를 보듯 이. 제이로는 역시');
insert into z_review values (129, 43, 'ikmy****', 'Y', 7, 1, '익숙한 설정을 답습하는 웹툰이.. 흥겨운 음악으로 포장되어 즐거움을 준다..');
insert into z_review values (130, 44, 'pose****', 'N', 6, 1, '앗싸 1빠 ! 영화 지금 봅니다');
insert into z_review values (133, 45, 'poin****', 'Y', 2, 289, '그나라 언어 나오면서 흥미 급하락...개연성없는 그나라 배우 나오면서 다 포기..그나마 후반이 볼건많았지만 각종 신파믹스로 인해 평점나락');
insert into z_review values (134, 45, 'siio****', 'Y', 1, 260, '역시 Made in China');
insert into z_review values (135, 45, 'appl****', 'Y', 6, 194, '영화가 시작하고 한자 로고가 보일때 걱정이 시작되었다');
insert into z_review values (139, 47, 'kkki****', 'Y', 2, 0, '말도안되는 반전에 고구마같은 답답함 그리고 짜증나듯');
insert into z_review values (140, 47, 'zxc1****', 'Y', 4, 0, '중반부에 밝혀지는 반전은 받아들이기 어려울 정도로 억지스럽고, 그 이후 별다른 긴장감 없이 그저 질질 끌고만 있는 후반부는 답답 그 자체다. 등장한 배우들이 너무 아깝다.');
insert into z_review values (142, 48, 'suns****', 'Y', 2, 77, '진짜 해도 너무 하다 할 정도로 이상한 영화...');
insert into z_review values (143, 48, 'sbtm****', 'N', 5, 10, '결말이 왜 없나요. 스토리는 몰입감 있는데 수술당한 사람들 다 어디갔나요');
insert into z_review values (144, 48, 'tjdg****', 'N', 6, 10, '유연석과 올가 쿠릴렌코가 썸타는 영화');
insert into z_review values (145, 49, 'ppy2****', 'N', 10, 80, '완벽합니다....눈물줄줄 흘렸습니다....겨울에 알맞은 영화...');
insert into z_review values (146, 49, 'dpdn****', 'N', 10, 48, '인류애 되찾는 영화.. 연말영화로 추천합니다!');
insert into z_review values (147, 49, 'cont****', 'N', 8, 5, '어린이는 사회의 등불임을 일깨워주는 따뜻한 작품');
insert into z_review values (148, 50, 'hhjk****', 'N', 5, 4, '평론가 3인은 뭐에 꽂혀서 7점씩이나 매겨 놓아서 사람을 낚냐. 살면서 카자흐스탄 영화도 봐봤다는 거에 의의를 둬야겠다. (연기랑 영화음악만 좋았음)');
insert into z_review values (149, 50, 'zoom****', 'Y', 6, 1, '연기도 연출도 다 어설퍼요 카자흐스탄 배경이라 색다르긴 했지만 그게 다인 영화');
insert into z_review values (150, 50, 'jsyb****', 'Y', 5, 1, '수사물로 봐도 스릴러로 봐도 시대물로 봐도 쓰리박자 골고루 아쉽다');

select * from z_review;